---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgDVNOIO3v+XzPC5y/2NHkUOyzResZfCVPDYKz+wasnmHezrxVVgkcmBCfVa7boqvTV+atO2sMN6GcEgQHfviJTeHzNV9KSU4GpCwmUPUJWAXrDcqZSbnFCA/TsP1hwlYYJ5j2zxmgnIZDYIX6Ye8+dtAsQpSl2WEhKvSqtB7MhnSluJG8MDiDumHnuNeVjCAbikCS1u4f5UDB2tYcPtCt3nPVnFFe+bICkIDYzLJij7iU0eqDSkDOjUCtcnJM14rJKzPDkAp/puxs9M54vRgN9cLWu2GyW/0xuhlQdToP4rl7jELuDKmv4Ypv9HZqDTIj+CRfzY6F47/GQTyIFk+RgoW6PAaBCyD02rlkSy7aC3vNIGiZ02f0b9lxDv6TKOA2ebssombcvYdubyLPS8IBwM2GwhgT0gWmjhBLOYrzoZ5GYD8qhVFF6LDFMrwNNJgqAt5Vwm/dLv+DwaSeFExbbgRvtSj69ooMulbOqZE8Ru3cukuRG4ykLsSyND8fky+fu/NDK/xiGRwssjYTACbXZTBuWSo6alHViJYn0W6EZbVCjPo2V3jCzHdKitZwz/urXhedBoIqesTwjFOntzazIXvj24g+DMRQ9z5VzEz5BNAy7RVCgzOmdI0aM59RZh6c3+8iqrpodWToY91ZzPCSXR+4bgkGkiWCc+lsR3EjKcNCYiweXA3lAf2HzVgYXtqkU8KNvObUB7MpfnHk8qpz6ntWsN3gJlEh4He0a0TWCIpkOjIeOzPMvG3LzcvR9jmCBxeQ==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
