---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAXvirojyGYIA0APy3CVxcoIIM+rLQ4ePxQ70a+v5hVIt/pW57XDtv9CS1WBXWe1ZgXynHKyVZstlrTgqX4aYce9IxbeDdd3+gQpQHL0vvNtqUxrkh+AdCx5Npq4e3keZFO7aOQQ7E8Zz6gwrQqhUl4tbqKnzm1WW/hIb615tSwzcVf5XUPcxeF9itmODl8Gi0iZAIdfRLtpm8fIca6CSLg82/1qRYmeWoFAHv1Q77FeIwMZ0/Olgl+mWyOlsvT2Jzu99teNT3mT08oJ6EIjkvE8mHQGm5VRL9l93f5tSbY9zjjZYd1MfrVM4wLRf2LgHOuolMjdjyzgQB2ExCTvc7fGhWLhzD3fw55WZ+uvKwB7JXBQnFeqM2NrL5OTh4bOZMzcCDT/GpPm/5BJlGQmZglzF9uk5YZjq4LP0Prp3TFg/cRUMMCc2w4NNznkxskMZ+JBNyNxa04KvMsv8FrDALVQTW1zPz9LfNQptO4qbgEpC0t2FNydsh07eb24JhyVdNow+t8KLdngx7tawYzLhhXvW52mCkTVlvkWu0Mr+Yi2HsQJXVNPGnLmcov2YNAJJS+Isse40Nb5OOPkb5mT8z0U45Ec5K26uSH0PxJzrlC3rOHnwqZZJ9SG4Gj+deew9hohzCWGskaKKZ/XGFtIhXCDf+/wgO7gkA3N5PpB9df44KY2RJsuHxf3ozLQUDFD4BHWG8im0WoGcrJY8hbaN2iAbPUJiz51oUFvopw3kB+FIAWCUbbGTGgGj7lrDn9I19+zA==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
